### ISSUE TITLE
Отслеживание кликов

### ISSUE THREAD

**Issue by DaniilSokolyuk** [redmanmale/afisha-daily-link-fix#1]
Сайты afisha.ru и daily.afisha.ru не отслеживают клики по внешим сайтам, это сделано для того чтоб роботы не видели ссылки на внешние сайты при индексировании страницы и хеш в урле нужен чтоб сервер не смог выполнить редирект на фишинговую страницу.
В случае рекламных компаний когда клик отслеживается в урле всегда есть ?utm_* это обычная практика
Спасибо ;)

**Comment by redmanmale** [comment]
@DaniilSokolyuk
Спасибо за пояснение. Уберу из описания фразу про отслеживание.

Но основная цель была именно в отображении ссылок, например, чтобы сохранить их или отправить.

**Comment by DaniilSokolyuk** [comment]
Тогда да, в этом плане не удобно конечно 👍, но таковы SEO требования, нельзя ссылочный вес домена понижать при индексации :)
